#==================================================
#| @compiler_testアクションのテスト用
#|
#| Nekozouneko Group Developer
#==================================================

command /test [<number>]:
    permission: actions.test
    permission message: &c実行権限がありません。
    trigger:
        set {_n} to getHash(arg-1)
        broadcast "%{_n}%"

function getHash(d: number = 0) :: number
    return mod({_d}, 10)