#==================================================
#| #Define.sk
#| 定数の管理モジュール
#|
#| Nekozouneko Group Developer
#==================================================
function handleDefine():
    #定義セクション
    set {define::DEVELOPMENT_MODE} to true

    #言語定義
    set {define::LANG::ERROR_INVALID_PARAMETER} to "&cパラメーターが不正です。"
    set {define::LANG::SUCCESS_COMMAND_GET_ITME} to "&aアイテムを付与しました。"

    set {define::LANG::ERROR_NOT_ENOUGH_MONEY} to "&cお金が足りません。"

    set {define::LANG::ERROR_BREAK_FROM_SURFACE} to "&cもっと地表に近いところから採掘してください！"

    set {define::LANG::SUCCESS_LEVELUP} to "&6&l修行屋 &8» &a&lLEVELUP!&8: &c${} &f→ &a${}"
    
    set {define::LANG::PORTAL_TELEPORTING} to "&a&lまもなくテレポートします..."
    set {define::LANG::PORTAL_TELEPORTED} to "&6&lテレポートしました！"
    set {define::LANG::PORTAL_CANCELLED} to "&c&lポータルから離れたためキャンセルされました。"
    set {define::LANG::ERROR_DESTINATION_NOT_AVAILABLE} to "&cテレポート中にエラーが発生しました。"

    set {define::LANG::SUCCESS_SHOP_SOLD} to "&6&l売店 &8» &aアイテムを売却しました。&f${}円&7を獲得しました。"
    set {define::LANG::ERROR_SHOP_SOLD_NOTHING} to "&6&l売店 &8» &c売れるアイテムがありませんでした。"

    set {define::LANG::SUCCESS_ENCHANTMENT} to "&6&lエンチャント &8» &aエンチャントしました！"

    set {define::LANG::ORES_REVIVE_1} to "&c&l鉱石復活 &4» &fまもなく鉱石が復活します..."
    set {define::LANG::ORES_REVIVE_2} to "&c&l鉱石復活 &4» &7まもなく鉱石が復活します..."
    set {define::LANG::ORES_REVIVED} to "&c&l鉱石復活 &4» &fすべての鉱石が復活しました！"

    add "&8========================================" to {define::LANG::QUEST_BASE::*}
    add "&6∵ &6&l${} ${} &6∴" to {define::LANG::QUEST_BASE::*}
    add "&7${}" to {define::LANG::QUEST_BASE::*}
    add "&r" to {define::LANG::QUEST_BASE::*}
    add "&3» 報酬" to {define::LANG::QUEST_BASE::*}
    add "${}" to {define::LANG::QUEST_BASE::*}
    add "&8========================================" to {define::LANG::QUEST_BASE::*}

    set {define::LANG::QUEST_DAILY} to "デイリークエスト"
    set {define::LANG::QUEST_WEEKLY} to "ウィークリークエスト"

    #Logs.sk
    set {define::LOGS_SAVE_PATH} to "themining.log"

    #ScoreBoard.sk
    set {define::SCOREBOARD_TITLE} to "&c&l The Mining"
    add "" to {define::SCOREBOARD_CONTENTS::*}
    add "&b🌐 現在地" to {define::SCOREBOARD_CONTENTS::*}
    add "&b・&f${}" to {define::SCOREBOARD_CONTENTS::*}
    add "" to {define::SCOREBOARD_CONTENTS::*}
    add "&bあなたの情報" to {define::SCOREBOARD_CONTENTS::*}
    add "&b・&fレベル &a${}" to {define::SCOREBOARD_CONTENTS::*}
    add "&b・&fEXP &b${}" to {define::SCOREBOARD_CONTENTS::*}
    add "&b・&f採掘数 &3${}" to {define::SCOREBOARD_CONTENTS::*}
    add "&b・&f所持金 &6${}円" to {define::SCOREBOARD_CONTENTS::*}
    add "" to {define::SCOREBOARD_CONTENTS::*}
    add "&8» &aSeason-2 公開！" to {define::SCOREBOARD_CONTENTS::*}
    add "&8» &7アップデート要望は" to {define::SCOREBOARD_CONTENTS::*}
    add "&8» &7Discordまで！" to {define::SCOREBOARD_CONTENTS::*}
    add "" to {define::SCOREBOARD_CONTENTS::*}
    add "&bwww.nekozouneko.net" to {define::SCOREBOARD_CONTENTS::*}

    #アイテム名の定義（Items.sk）
    set {define::LANG_ITEMS::stone} to "石"
    set {define::LANG_ITEMS::coal ore} to "石炭"
    set {define::LANG_ITEMS::iron ore} to "鉄"
    set {define::LANG_ITEMS::lapis ore} to "ラピスラズリ"

    set {define::LANG_ENCHANTMENTS::efficiency} to "効率強化"
    set {define::LANG_ENCHANTMENTS::fortune} to "幸運"
    set {define::LANG_ENCHANTMENTS::auto_collect} to "自動回収"
    set {define::LANG_ENCHANTMENTS::auto_sell} to "自動売却"
    set {define::LANG_ENCHANTMENTS::range_mining} to "範囲採掘"

    #アイテムの定義（Items.sk）
    set {define::ITEMS::COBBLESTONE} to cobblestone named "&a丸石"
    set {define::ITEMS::COAL} to coal named "&a石炭"
    set {define::ITEMS::RAW_IRON} to raw iron named "&a鉄の原石" with lore "&6精錬NPCで焼けるよ！"
    set {define::ITEMS::IRON_INGOT} to iron ingot named "&a鉄インゴット"
    set {define::ITEMS::LAPIS_LAZULI} to lapis lazuli named "&aラピスラズリ" with lore "&6エンチャントに使えるよ！"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::COBBLESTONE} to "COBBLESTONE"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::COAL} to "COAL"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::RAW_IRON} to "RAW_IRON"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::IRON_INGOT} to "IRON_INGOT"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::LAPIS_LAZULI} to "LAPIS_LAZULI"

    #ピッケルの定義（Items.sk）
    set {define::ITEMS::FIRST_PICKAXE} to unbreakable golden pickaxe of efficiency 1 named "&d初期ピッケル"
    set {define::ITEMS::BLUE_PICKAXE} to unbreakable diamond pickaxe of efficiency 1 named "&bブルーピッケル"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::FIRST_PICKAXE} to "FIRST_PICKAXE"
    set string tag "TheMining;ItemId" of custom nbt of {define::ITEMS::BLUE_PICKAXE} to "BLUE_PICKAXE"

    #破壊可能鉱石の定義（Ores.sk）
    add stone to {define::BREAKABLE_ORES::FIRST_PICKAXE::*}
    add coal ore to {define::BREAKABLE_ORES::FIRST_PICKAXE::*}
    add iron ore to {define::BREAKABLE_ORES::FIRST_PICKAXE::*}

    add stone to {define::BREAKABLE_ORES::BLUE_PICKAXE::*}
    add iron ore to {define::BREAKABLE_ORES::BLUE_PICKAXE::*}
    add lapis ore to {define::BREAKABLE_ORES::BLUE_PICKAXE::*}

    #エンチャント可能なピッケル定義
    add "FIRST_PICKAXE" to {define::ENCHANTMENT::ENCHANTABLE_ITEMS::*}
    add "BLUE_PICKAXE" to {define::ENCHANTMENT::ENCHANTABLE_ITEMS::*}

    #エンチャント種類のリスト定義（Enchantment.sk）
    add "efficiency" to {define::ENCHANTMENT_TYPES::*}
    add "fortune" to {define::ENCHANTMENT_TYPES::*}
    add "auto_collect" to {define::ENCHANTMENT_TYPES::*}
    add "auto_sell" to {define::ENCHANTMENT_TYPES::*}
    add "range_mining" to {define::ENCHANTMENT_TYPES::*}

    #エンチャント最大レベルの定義
    set {define::ENCHANTMENT::MAX_LEVEL::efficiency} to 20
    set {define::ENCHANTMENT::MAX_LEVEL::fortune} to 20
    set {define::ENCHANTMENT::MAX_LEVEL::auto_collect} to 1
    set {define::ENCHANTMENT::MAX_LEVEL::auto_sell} to 10
    set {define::ENCHANTMENT::MAX_LEVEL::range_mining} to 3

    #エンチャント初期EXPコスト（初項）の定義
    set {define::ENCHANTMENT::INITIAL_TERM::efficiency} to 20
    set {define::ENCHANTMENT::INITIAL_TERM::fortune} to 50
    set {define::ENCHANTMENT::INITIAL_TERM::auto_collect} to 20
    set {define::ENCHANTMENT::INITIAL_TERM::auto_sell} to 50
    set {define::ENCHANTMENT::INITIAL_TERM::range_mining} to 200

    #エンチャントコスト増加量（公比）の定義
    set {define::ENCHANTMENT::COMMON_RATIO::efficiency} to 2
    set {define::ENCHANTMENT::COMMON_RATIO::fortune} to 2
    set {define::ENCHANTMENT::COMMON_RATIO::auto_collect} to 2
    set {define::ENCHANTMENT::COMMON_RATIO::auto_sell} to 2
    set {define::ENCHANTMENT::COMMON_RATIO::range_mining} to 2

    #ピッケルのエンチャント定義（Items.sk）
    set int tag "TheMining;Enchantments;efficiency" of custom nbt of {define::ITEMS::FIRST_PICKAXE} to 1
    set int tag "TheMining;Enchantments;efficiency" of custom nbt of {define::ITEMS::BLUE_PICKAXE} to 1

    #エンチャント台の場所定義
    add location(-81.0, 80.0, 37.0, world "world", 0, 0) to {define::ENCHANTMENT::TABLE_LOCATION::*}

    #ピッケルの表記化（Items.sk）
    set {define::ITEMS::FIRST_PICKAXE} to toPickaxeFormat({define::ITEMS::FIRST_PICKAXE})
    set {define::ITEMS::BLUE_PICKAXE} to toPickaxeFormat({define::ITEMS::BLUE_PICKAXE})

    #ドロップアイテムの定義（Ores.sk）
    set {define::DROP_ITEMS::stone} to getItemData("COBBLESTONE")
    set {define::DROP_ITEMS::coal ore} to getItemData("COAL")
    set {define::DROP_ITEMS::iron ore} to getItemData("RAW_IRON")
    set {define::DROP_ITEMS::lapis ore} to getItemData("LAPIS_LAZULI")

    #採掘時の獲得経験値の定義（Ores.sk）
    set {define::EARN_EXP::stone} to 0.1
    set {define::EARN_EXP::coal ore} to 0.2
    set {define::EARN_EXP::iron ore} to 0.2
    set {define::EARN_EXP::lapis ore} to 0.3

    #5Tickあたりに処理する鉱石復活数（Ores.sk
    set {define::REVIVE_ORE_PER_INTERVAL} to 200

    #鉱石復活間隔（Ores.sk）
    set {define::REVIVE_INTERVAL} to 300 second

    #鉱石復活箇所Schematicの定義（〇〇.schem）
    add "mine01" to {define::REVIVE_ORE_SCHEMATICS::*}
    add "mine02" to {define::REVIVE_ORE_SCHEMATICS::*}

    #NPC種類の定義（NPCs.sk）
    add "LEVELUP" to {define::NPCS::*}
    add "SHOP" to {define::NPCS::*}
    add "SMELTING" to {define::NPCS::*}
    add "QUEST_MASTER" to {define::NPCS::*}

    #レベルアップ用NPCの定義（NPCs.sk）
    set {define::NPC::LEVELUP::NAME} to "&6&l修行屋のおじさん &7[クリック]"
    set {define::NPC::LEVELUP::SKIN} to "Tomato_dayo"
    set {define::NPC::LEVELUP::LOCATION} to location(-101.5, 71, -23.5, world "world", -30, 0)
    set {define::NPC::SHOP::NAME} to "&a&l売店 &7[クリック]"
    set {define::NPC::SHOP::SKIN} to "nekokazokuL"
    set {define::NPC::SHOP::LOCATION} to location(-93.5, 71, -17.5, world "world", 100, 0)
    set {define::NPC::SMELTING::NAME} to "&d精錬 &7[クリック]"
    set {define::NPC::SMELTING::SKIN} to "nekozouneko"
    set {define::NPC::SMELTING::LOCATION} to location(-124.5, 75, 8.5, world "world", -90, 0)
    set {define::NPC::QUEST_MASTER::NAME} to "&6クエストマスター &7[クリック]"
    set {define::NPC::QUEST_MASTER::SKIN} to "Yeahn"
    set {define::NPC::QUEST_MASTER::LOCATION} to location(-146.5, 80.5, 23.5, world "world", -90, 0)

    #レベルアップのコスト計算（profile.sk）
    set {define::LEVELUP_INITIAL_TERM} to 2000 #初項
    set {define::LEVELUP_COMMON_RATIO} to 2 #公比

    #Destination定義（Map.sk）
    set {define::LOCATION::LOBBY} to location(-83.5, 67.6, 4.5, world "world", 140, 0)
    set {define::LOCATION::MINING_1} to location(-164.5, 115.1, 246.5, world "world", 90, 0)
    set {define::LOCATION::MINING_2} to location(89.0, 113.1, 291.0, world "world", 135, 0)

    #ポータル一覧の定義（Map.sk）
    add "M1-TO-LOBBY" to {define::PORTALS::*}
    add "LOBBY-TO-M1" to {define::PORTALS::*}
    add "M2-TO-LOBBY" to {define::PORTALS::*}
    add "LOBBY-TO-M2" to {define::PORTALS::*}

    #ポータルリンクの定義（Map.sk）
    set {define::PORTAL_DESTINATION::M1-TO-LOBBY} to "LOBBY"
    set {define::PORTAL_DESTINATION::LOBBY-TO-M1} to "MINING_1"
    set {define::PORTAL_DESTINATION::M2-TO-LOBBY} to "LOBBY"
    set {define::PORTAL_DESTINATION::LOBBY-TO-M2} to "MINING_2"

    #ポータル範囲定義（Map.sk）
    set {define::PORTAL::M1-TO-LOBBY::1} to location(-152.0, 116.0, 252.0, world "world", 0, 0)
    set {define::PORTAL::M1-TO-LOBBY::2} to location(-155.0, 126.5, 240.0, world "world", 0, 0)
    set {define::PORTAL::LOBBY-TO-M1::1} to location(-25.0, 65, -66.0, world "world", 0, 0)
    set {define::PORTAL::LOBBY-TO-M1::2} to location(-26.0, 68, -67.0, world "world", 0, 0)
    set {define::PORTAL::M2-TO-LOBBY::1} to location(88, 113, 294, world "world", 0, 0)
    set {define::PORTAL::M2-TO-LOBBY::2} to location(92.0, 117, 293.0, world "world", 0, 0)
    set {define::PORTAL::LOBBY-TO-M2::1} to location(-70.0, 71, -74.0, world "world", 0, 0)
    set {define::PORTAL::LOBBY-TO-M2::2} to location(-71.0, 74, -77.0, world "world", 0, 0)

    #場所定義（Map.sk）
    add "LOBBY" to {define::REGIONS::*}
    add "M1" to {define::REGIONS::*}
    add "M2" to {define::REGIONS::*}

    #場所範囲定義（Map.sk）
    set {define::REGION::LOBBY::1} to location(-227.6, 0, -144.5, world "world", 0, 0)
    set {define::REGION::LOBBY::2} to location(32.5, 300, 115.5, world "world", 0, 0)
    set {define::REGION::M1::1} to location(-314.5, 0, 377.5, world "world", 0, 0)
    set {define::REGION::M1::2} to location(-142.5, 300, 160.5, world "world", 0, 0)
    set {define::REGION::M2::1} to location(156.5, 0, 357.5, world "world", 0, 0)
    set {define::REGION::M2::2} to location(-35.5, 300, 165.5, world "world", 0, 0)

    #場所の名前定義（Map.sk）
    set {define::REGION_NAME::LOBBY} to "広場"
    set {define::REGION_NAME::M1} to "採掘所1"
    set {define::REGION_NAME::M2} to "採掘所2"

    #売店の売却価格の定義（Shop.sk）
    set {define::SELL_PRICE::COBBLESTONE} to 0.5
    set {define::SELL_PRICE::COAL} to 1.0
    set {define::SELL_PRICE::IRON_INGOT} to 1.5
    set {define::SELL_PRICE::LAPIS_LAZULI} to 3.0

    #製錬アイテムの紐付け（Smelting.sk）
    set {define::SMELTING_ITEM::RAW_IRON} to "IRON_INGOT"

    #クエスト割り当て最大数の定義（Quest.sk）
    set {define::QUEST_DAILY_ASSIGN_MAX} to 10
    set {define::QUEST_WEEKLY_ASSIGN_MAX} to 5

    #クエストの完了チェックハンドラーのチェック間隔
    set {define::QUEST_CHECK_INTERVAL} to 1 second

    #クエストIDの定義（Quest.sk）
    add "SAVING_MONEY_500" to {define::QUESTS::*}
    add "SAVING_MONEY_1000" to {define::QUESTS::*}
    add "SAVING_MONEY_5000" to {define::QUESTS::*}
    add "SELL_ITEM_100" to {define::QUESTS::*}
    add "VISIT_ANY_MINE" to {define::QUESTS::*}
    add "ENCHANT_PICKAXE_ONCE" to {define::QUESTS::*}

    #クエスト種類の紐付け（Quest.sk）
    #1: デイリークエスト
    #2: ウィークリークエスト
    set {define::QUEST_TYPE::SAVING_MONEY_500} to 1
    set {define::QUEST_TYPE::SAVING_MONEY_1000} to 1
    set {define::QUEST_TYPE::SAVING_MONEY_5000} to 1
    set {define::QUEST_TYPE::SELL_ITEM_100} to 1
    set {define::QUEST_TYPE::VISIT_ANY_MINE} to 1
    set {define::QUEST_TYPE::ENCHANT_PICKAXE_ONCE} to 1

    #クエスト名の紐付け（Quest.sk）
    set {define::QUEST_TITLE::SAVING_MONEY_500} to "お金を500円貯める"
    set {define::QUEST_TITLE::SAVING_MONEY_1000} to "お金を1,000円貯める"
    set {define::QUEST_TITLE::SAVING_MONEY_5000} to "お金を5,000円貯める"
    set {define::QUEST_TITLE::SELL_ITEM_100} to "アイテムを100個売る"
    set {define::QUEST_TITLE::VISIT_ANY_MINE} to "いずれかの採掘所に訪れる"
    set {define::QUEST_TITLE::ENCHANT_PICKAXE_ONCE} to "ピッケルにエンチャントする"

    #完了トリガー数の紐付け（Quest.sk）
    set {define::QUEST_COMPLETE_TRIGGER::SAVING_MONEY_500} to 1
    set {define::QUEST_COMPLETE_TRIGGER::SAVING_MONEY_1000} to 1
    set {define::QUEST_COMPLETE_TRIGGER::SAVING_MONEY_5000} to 1
    set {define::QUEST_COMPLETE_TRIGGER::SELL_ITEM_100} to 100
    set {define::QUEST_COMPLETE_TRIGGER::VISIT_ANY_MINE} to 1
    set {define::QUEST_COMPLETE_TRIGGER::ENCHANT_PICKAXE_ONCE} to 1

    #クエスト報酬の紐付け（Quest.sk）
    #{define::QUEST_REWARD::<QuestID>::<報酬の種類>}に値を入れる
    #報酬の種類は、EXPまたはMONEY
    set {define::QUEST_REWARD::SAVING_MONEY_500::EXP} to 50
    set {define::QUEST_REWARD::SAVING_MONEY_1000::EXP} to 100
    set {define::QUEST_REWARD::SAVING_MONEY_5000::EXP} to 150
    set {define::QUEST_REWARD::SELL_ITEM_100::EXP} to 50
    set {define::QUEST_REWARD::VISIT_ANY_MINE::EXP} to 50
    set {define::QUEST_REWARD::ENCHANT_PICKAXE_ONCE::MONEY} to 100

    #会話IDの登録（Talk.sk）
    add "LEVELUP" to {define::TALKS::*}

    #話者の紐付け（Talk.sk）
    set {define::TALK_SPEAKER::LEVELUP} to "修行屋のおじさん"

    #会話IDのループ設定
    set {define::TALK_LOOPING::LEVELUP} to false

    #会話内容の登録（Talk.sk）
    #DTMのように、会話開始時から何秒目（0スタート）にどのメッセージを表示するかで定義します。
    set {define::TALK_CONTENT::LEVELUP::0} to "どうしてこんな集落に落ちてきてしまったんだい？"
    set {define::TALK_CONTENT::LEVELUP::4} to "この集落に一度でも来てしまったならば、生涯ここで過ごすことになるだろうね。"
    set {define::TALK_CONTENT::LEVELUP::9} to "私はこの集落で、修行屋をやってるよ。"
    set {define::TALK_CONTENT::LEVELUP::12} to "レベルアップがしたかったら、ここにおいで。"

    #DEVELOPMENT_MODE用のOverride
    if getDefine("DEVELOPMENT_MODE") is true:
        set {define::REVIVE_INTERVAL} to 30 second

function initDefine():
    clear {define::*}
    handleDefine()

function getDefine(defineName: string) :: object:
    return {define::%{_defineName}%}

function getDefineList(defineListName: string) :: objects:
    return {define::%{_defineListName}%::*}

function getIndexList(defineListName: string) :: objects:
    loop {define::%{_defineListName}%::*}:
        add loop-index parsed as integer to {_indexes::*}
    return {_indexes::*}


function getDistributionURL(path: string) :: string:
    return "https://raw.githubusercontent.com/TeamNekozouneko/TheMiningS2/refs/heads/master/distribution/%{_path}%"