#==================================================
#| #Events.sk
#| イベントの管理モジュール
#|
#| Nekozouneko Group Developer
#==================================================

on load:
    main()
    oreReviveAsyncHandler()

every second:
    loop all players:
        scoreboardUpdate(loop-player)

on join:
    profileInit(player)

on break:
    cancel drops
    cancel event if breakHandle(player, event-block) is false