#==================================================
#| #Utils.sk
#| 数式関数や変換関数の実装モジュール
#|
#| Nekozouneko Group Developer
#==================================================

function String(value: object) :: string:
    return "%{_value}%"

function getLevelupCost(currentLevel: integer) :: number:
    set {_initial_term} to 2000
    set {_common_ratio} to 2
    return {_initial_term} * {_common_ratio} ^ ({_currentLevel}-1)