name: Compiler test
on: [push]

jobs:
  compiler_test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # GraalVM 21をインストール
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      # Minecraft Serverをセットアップ
      - name: Set up Minecraft Server
        run: |
          wget https://api.papermc.io/v2/projects/paper/versions/1.21.3/builds/82/downloads/paper-1.21.3-82.jar -O ~/server.jar
          java -jar ~/server.jar nogui
          sed -i 's/false/true/g' eula.txt

      # Minecraft Serverのランタイム検証
      - name: Run Minecraft Server for Runtime test
        run: echo "stop" | java -jar ~/server.jar nogui
