name: テスト
on: [push]

jobs:
  RuntimeExecution:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # GraalVM 21をインストール
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      # Minecraft Serverをセットアップ
      - name: Set up Minecraft Server
        run: |
          wget https://api.papermc.io/v2/projects/paper/versions/1.21.3/builds/82/downloads/paper-1.21.3-82.jar -O ~/server.jar
          (cd ~ && java -jar server.jar nogui)
          sed -i 's/false/true/g' ~/eula.txt

      #プラグイン環境のセットアップ
      - name: Set up plugin environments
        run: |
          mkdir -p ~/plugins/Skript/scripts/
          mv .github/workflows/plugins/Skript-2.10.1.jar ~/plugins/
          mv .github/workflows/plugins/SkBee-3.8.2.jar ~/plugins/
          mv .github/workflows/plugins/Citizens-2.0.36-b3644.jar ~/plugins/
          mv .github/workflows/plugins/Skonic-1.2.2.jar ~/plugins/
          cp -r * ~/plugins/Skript/scripts/
          cp -r .github/workflows/testCase/* ~/plugins/Skript/scripts/
          cp .github/workflows/golang/check ~
      
      # Minecraft Serverのランタイム実行
      - name: Run Minecraft Server for Runtime test
        run: (cd ~ && java -jar server.jar nogui)
      
      # コンパイル・ランタイムテストの結果処理
      - name: Check result of Runtime and Compile
        run: (cd ~ && ./check)
